### ISSUE TITLE
Jenkins plugins stopped working over the weekend

### ISSUE THREAD

**Issue by mkocikowski** [deeplearning4j/ops#10]
today (jan 25 2016) the same jenkins setup script which was working last week is no longer producing a working jenkins installation - plugins are not being updated, are not available for download.
```
Jan 25, 2016 10:03:27 PM hudson.model.UpdateSite updateData
SEVERE: ERROR: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Algorithm constraints check failed: MD5withRSA<br>	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)<br>	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)<br>	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br>	at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br>	at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:76)<br>	at hudson.model.UpdateSite.verifySignature(UpdateSite.java:222)<br>	at hudson.model.UpdateSite.updateData(UpdateSite.java:201)<br>	at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:173)<br>	at hudson.PluginManager.doCheckUpdatesServer(PluginManager.java:959)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<brat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)<br>	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:46)<br>	at org.kohsuke.stapler.Function$InterceptedFunction.invoke(Function.java:399)<br>	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)<br>	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)<br>	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)<br>	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)<br>	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)<br>	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)<br>	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:183)<br>	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)<br>	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)<br>	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)<br>	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)<br>	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)<br>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br>	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)<br>	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)<br>	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br>	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br>	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)<br>	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)<br>	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br>	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br>	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)<br>	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)<br>	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)<br>	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)<br>	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)<br>	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)<br>	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)<br>	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)<br>	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)<br>	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)<br>	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)<br>	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)<br>	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)<br>	at org.eclipse.jetty.server.Server.handle(Server.java:370)<br>	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)<br>	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)<br>	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)<br>	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)<br>	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)<br>	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)<br>	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)<br>	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)<br>	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)<br>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br>	at java.lang.Thread.run(Thread.java:745)<br></pre>
```

**Comment by mkocikowski** [comment]
I tried downgrading Jenkins, but that didn't work. I think it has to do with a Java security update which bumped the minimum length of certificate key to 1024. See `jdk.certpath.disabledAlgorithms=` in  `/etc/alternatives/java_sdk/jre/lib/security/java.security`  Shortening it to 512 makes things work again.
